name: gaia
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/CHANGELOG.md'
  pull_request:

jobs:          
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.0
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SEMANTIC_RELEASE_PACKAGE: ${{ github.workflow }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            semantic-release-slack-bot

  build-publish:
    runs-on: ubuntu-latest
    needs: semantic-release
    strategy:
      matrix:
        context: [hub, reader, admin]
    env:
      IMAGE_NAME: blockstack/${{ github.workflow }}-${{ matrix.context }}

    steps:
      - uses: actions/checkout@v2

      - name: Notify slack start
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          channel: devops-notify
          status: STARTING
          color: warning

      - name: Build/Tag/Push Image - Quay
        uses: docker/build-push-action@v1
        with:
          repository: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
          path: ${{ matrix.context }}
          tags: ${{ needs.semantic-release.outputs.new_release_version }}
          tag_with_ref: true
          add_git_labels: true
          # Only push if there's a new release on main branch, or if building a non-main branch
          push: ${{ github.ref != 'refs/heads/master' || needs.semantic-release.outputs.new_release_version != '' }}

      - name: Build/Tag/Push Image - Dockerhub
        uses: docker/build-push-action@v1
        with:
          repository: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          path: ${{ matrix.context }}
          tags: ${{ needs.semantic-release.outputs.new_release_version }}
          tag_with_ref: true
          add_git_labels: true
          # Only push if there's a new release on main branch, or if building a non-main branch
          push: ${{ github.ref != 'refs/heads/master' || needs.semantic-release.outputs.new_release_version != '' }}

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: devops-notify
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: devops-notify
          status: FAILED
          color: danger
